# Generated by Django 4.1.7 on 2023-03-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('uname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('paswd', models.CharField(max_length=255)),
                ('cpaswd', models.CharField(max_length=255)),
            ],
        ),
    ]
